import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MatCheckboxModule, 
  MatButtonModule, 
  MatInputModule, 
  MatAutocompleteModule, 
  MatDatepickerModule, 
  MatFormFieldModule, 
  MatRadioModule, 
  MatSelectModule, 
  MatSliderModule, 
  MatSlideToggleModule, 
  MatMenuModule, 
  MatSidenavModule, 
  MatToolbarModule, 
  MatListModule, 
  MatGridListModule, 
  MatCardModule, 
  MatStepperModule, 
  MatTabsModule, 
  MatExpansionModule, 
  MatButtonToggleModule, 
  MatChipsModule, 
  MatIconModule, 
  MatProgressSpinnerModule, 
  MatProgressBarModule, 
  MatDialogModule, 
  MatTooltipModule, 
  MatSnackBarModule, 
  MatTableModule, 
  MatSortModule, 
  MatPaginatorModule, 
  MatBadgeModule
} from '@angular/material';
import { MatProgressButtonsModule } from 'mat-progress-buttons';
import { ReactiveFormsModule, FormsModule } from '@angular/forms';

@NgModule({
  imports: [
    CommonModule,
    MatCheckboxModule,
    MatCheckboxModule,
    MatButtonModule,
    MatInputModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatFormFieldModule,
    MatRadioModule,
    MatSelectModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatMenuModule,
    MatSidenavModule,
    MatToolbarModule,
    MatListModule,
    MatGridListModule,
    MatCardModule,
    MatStepperModule,
    MatTabsModule,
    MatExpansionModule,
    MatButtonToggleModule,
    MatChipsModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatDialogModule,
    MatTooltipModule,
    MatSnackBarModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
    MatProgressButtonsModule,
    MatBadgeModule,
    ReactiveFormsModule,
  ],
  exports: [
    CommonModule,
    MatCheckboxModule,
    MatCheckboxModule,
    MatButtonModule,
    MatInputModule,
    MatAutocompleteModule,
    MatDatepickerModule,
    MatFormFieldModule,
    MatRadioModule,
    MatSelectModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatMenuModule,
    MatSidenavModule,
    MatToolbarModule,
    MatListModule,
    MatGridListModule,
    MatCardModule,
    MatStepperModule,
    MatTabsModule,
    MatExpansionModule,
    MatButtonToggleModule,
    MatChipsModule,
    MatIconModule,
    MatProgressSpinnerModule,
    MatProgressBarModule,
    MatDialogModule,
    MatTooltipModule,
    MatSnackBarModule,
    MatTableModule,
    MatSortModule,
    MatPaginatorModule,
    MatProgressButtonsModule,
    MatBadgeModule,
    ReactiveFormsModule,
    FormsModule
  ],
  declarations: [],
})
export class MatModuleModule { }
